name: Run Jest Tests with MySQL

on:
  push:
    branches:
      - test
  pull_request:
    branches: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 
          container port: 3306 
          character set server: "utf8" 
          collation server: "utf8_general_ci" 
          mysql version: "5.7"
          mysql database: testing 
          mysql user: root
          mysql root password: passwordRoot

      - name: Wait for MySQL to be ready
        run: |
          until docker exec $(docker ps --filter "ancestor=mysql:5.7" --format "{{.ID}}") mysqladmin ping -uroot -ppasswordRoot --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done
      
      - name: Start Redis
        uses: supercharge/redis-github-action@1.8.1
        with:
          redis-version: "7"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install mysql client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Apply DB structure
        run: |
          mysql -h127.0.0.1 -P3306 -uroot -ppasswordRoot testing < demo/db/structure.demo.sql

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
